/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ROOT_H_RPCGEN
#define _ROOT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct terms {
	int a;
	int b;
	int c;
};
typedef struct terms terms;

struct roots {
	float s1;
	float s2;
};
typedef struct roots roots;

#define ROOT_PROGRAM 0x20000001
#define ROOT_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define root 1
extern  roots * root_1(terms *, CLIENT *);
extern  roots * root_1_svc(terms *, struct svc_req *);
extern int root_program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define root 1
extern  roots * root_1();
extern  roots * root_1_svc();
extern int root_program_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_terms (XDR *, terms*);
extern  bool_t xdr_roots (XDR *, roots*);

#else /* K&R C */
extern bool_t xdr_terms ();
extern bool_t xdr_roots ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ROOT_H_RPCGEN */
