/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "root.h"
#include <math.h>
roots *
root_1_svc(terms *argp, struct svc_req *rqstp)
{
	static roots  result;
	float D = argp->b * argp->b - 4*argp->a * argp->c;
	float s1 = ((-1)*argp->b - sqrt(D))/2;  
	float s2 = (argp->b - sqrt(D))/2;
	
	result.s1 = s1;
	result.s2 = s2; 

	return &result;
}
