/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "root.h"

bool_t
xdr_terms (XDR *xdrs, terms *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->c))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_roots (XDR *xdrs, roots *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->s1))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->s2))
		 return FALSE;
	return TRUE;
}
