/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "root.h"


void
root_program_1(char *host,int a ,int b,int c)
{
	CLIENT *clnt;
	roots  *result_1;
	terms  root_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ROOT_PROGRAM, ROOT_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	root_1_arg.a = a;
	root_1_arg.b = b;
	root_1_arg.c = c;
	
	result_1 = root_1(&root_1_arg, clnt);
	if (result_1 == (roots *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("The results are %f and %f\n", result_1->s1,result_1->s2);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int a,b,c;
	if (argc < 4) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	a = argv[2];
	b = argv[3];
	c = argv[4];

	root_program_1 (host,a,b,c);
exit (0);
}
